### ISSUE TITLE
Localized error message

### ISSUE THREAD

**Issue by eserte** [johannessen/neo4j-driver-perl#12] opened 2021-02-08 06:59 UTC
The test suite fails on some of my smoker systems like this:
```
    #   Failed test 'create https with tls_ca'
    #   at t/config.t line 174.
    # expecting: Regexp ((?^i:\bfoo\..*\b(?:No such file|does not exist)\b))
    # found: HTTP error: 500 SSL_ca_file foo. can't be used: Datei oder Verzeichnis nicht gefunden on GET to /
    # SSL_ca_file foo. can't be used: Datei oder Verzeichnis nicht gefunden at /opt/perl-5.20.3/lib/site_perl/5.20.3/IO/Socket/SSL.pm line 523.
    #  at t/config.t line 173.
    # Looks like you failed 1 test of 6.

#   Failed test 'tls'
#   at t/config.t line 187.
# Looks like you failed 1 test of 11.
t/config.t ............ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests 
```
I think this happens if a non-English locale is in effect (e.g. `LC_ALL=de_DE.UTF-8`) and it's an older perl (<=5.20.3).

**Comment by johannessen** [comment] 2021-02-08 12:47
Right. Thanks for opening the issue!

**Comment by johannessen** [comment] 2021-02-13 13:43
Fixed in [release 0.22](https://metacpan.org/release/AJNN/Neo4j-Driver-0.22).

The test now works as intended, with CPAN Testers exposing what might be an incompatibility with an older SSL lib version. I hope to have this fixed as well by the next release.

CPAN Testers rocks!

**Closed as completed by johannessen** 2021-02-13 13:43 UTC
Labels: bug
