### ISSUE TITLE
possible memory leak in list

### ISSUE THREAD

**Issue by AndreaAstronaut** [johannessen/neo4j-driver-perl#17] opened 2024-10-31 11:52 UTC
This is related to the issue I opened against perlbolt last week: [https://github.com/majensen/perlbolt/issues/61#issue-2604989995](https://github.com/majensen/perlbolt/issues/61#issue-2604989995)
As neo4j-driver-perl uses perlbolt I was hoping that the fix for the perlbolt memory leak would address the issue I am seeing here as well. 
But it seems it does not.
While on the same system things work fine using perlbolt(neo4j::Bolt 0.4206) to query neo4j directly, if I involve the driver I am still observing a memory leak.
I tried to track it down, it seems to be coming from anything that involves list (fetch, size, list, single-get). 
I do not observe any leak for result->keys.

Below are the scenarios I tried using the movies database available to download here:
https://github.com/neo4j-graph-examples/movies.

```
my $driver = Neo4j::Driver->new('bolt://localhost)->basic_auth('user', 'password');

my $query = 'MATCH (keanu:Person {name:"Keanu Reeves"}) RETURN keanu.born AS born';

my $session = $driver->session(database => "movies");

my $iterationCount = 0;
while ($iterationCount < 100000) {
    $iterationCount++;
 ## Try 1 and 2 => mem leak
  # my @records = $session->run($query)->list;
 ## below uses twice as memory ....
  # my $transaction = $session->begin_transaction;
  # my @records = $transaction->run($query)->list;
  # $transaction->commit;
  # foreach my $record ( @records ) {
   #   print "Iteration $iterationCount: " . $record->get('born'). "\n";
   #}
 ## Try 3 => leak
 ## stream result records
  # $result = $session->run($query);
  # while ( $record = $result->fetch ) {
  #      print "Iteration $iterationCount: " . $record->get('born'). "\n";
  # }
 ## Try 4 => leak
 ## try results only and check size (without list)
  # $result = $session->run($query);
  # $record_count = $result->size;
  # print "Iteration $iterationCount has this many records:" . $record_count. "\n";
  # @records = $result->list;
 ## Try 5 => NO leak
 ## try results only
  # $result = $session->run($query);
  # print "Iteration $iterationCount no result access\n";
 ## Try 6 => leak
 ## shortcut for results with a single record only
  # $name = $session->run($query)->single->get('born'); 
  # print "Iteration $iterationCount: " . $name. "\n";
 ## Try 7 => no leak
 ## check keys only (no buffer here)
  # $result = $session->run($query);
  # @names = $result->keys;
  # print "Iteration $iterationCount: "  . Dumper(@names) ."\n";

    if ( $iterationCount % 10000 == 0 ) {
       sleep( $sleep_seconds );
    }
}
```

I am using the most recent Neo4j::Driver and Neo4j::Bolt 0.4206 (fix-memory-leaks branch) and previously I used Neo4j::Bolt 0.4203.
I encountered this on Oracle Linux 7 running Neo4j 5.13 and Perl 5.16.3. Neo4j::Client 0.46 (also tried 0.52).

This is also happening on Oracle Linux 8 with Perl version 5.38.2 and the same versions of Neo4j::Bolt and Neo4j::Client, Neo4j::Driver.

**Comment by johannessen** [comment] 2024-10-31 22:03
Hi @AndreaAstronaut, thanks for your report! While I can reproduce the issues, I haven’t found the cause yet. Investigating.

**Comment by johannessen** [comment] 2024-11-01 12:08
It turns out these memory leaks are in Neo4j::Bolt, not in Neo4j::Driver. I’ve pushed fixes for them (and for a few more leaks) to the [**perlbolt/fix-memory-leaks**](https://github.com/majensen/perlbolt/tree/fix-memory-leaks) branch.

Hopefully that’ll resolve this issue for you. Thanks again for your efforts in reporting this! Please do feel free to get in touch if you notice anything else.

**Closed as completed** 2024-11-08 02:53 UTC
